name: 💡 Feature Request
description: Propose a new feature for the platform
labels: [needs-triage, feature-request]
body:
- type: textarea
  attributes:
    label: Description
    description: Describe the feature
- type: dropdown
  id: estimation
  attributes:
    label: Have you provided an initial effort estimate for this issue?
    description: See our [handbook](https://flowforge.com/handbook/development/releases/planning/#effort-estimation) for more details.
    multiple: false
    options:
      - I have provided an initial effort estimate
      - I am no FlowForge team member
      - I can not provide an initial effort estimate
  validations:
      required: true
