forge:
  domain: flowfuse.dev
  https: true
  localPostgresql: true
  localValkey: false
  projectIngressClassName: traefik
  broker:
    enabled: true
    teamBroker:
      enabled: true
  cloudProvider: aws
  cache:
    type: memory
  email:
    ses:
      region: eu-west-1
  assistant:
    enabled: true
  expert:
    enabled: true
    insights:
      enabled: true
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 16Mi
  rate_limits:
    enabled: true
    global: false
    max: 600
    maxAnonymous: 10
    timeWindow: 30000
  tables:
    enabled: true
    driver:
      type: postgres-localfs
      options:
        database:
          port: 5432
          database: postgres
          ssl: false
  telemetry:
    enabled: true
    frontend:
      posthog:
        apiurl: https://eu.posthog.com
        capture_pageview: false

postgresql:
  persistence:
    enabled: false
  primary:
    nodeAffinityPreset:
      type: "hard"
      key: "role"
      values:
        - "management"

ingress:
  className: traefik
