name: Install Test
on:
  schedule:
    - cron: '45 23 * * *'
  workflow_dispatch:

jobs:
  install:
    name: Install and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
      - name: install
        run: |
          npm install @flowfuse/flowfuse
          mkdir etc var
          cp node_modules/@flowfuse/flowfuse/etc/flowforge.yml etc/
          ls -lh node_modules/.bin
      - name: start server in background
        uses: JarvusInnovations/background-action@2428e7b970a846423095c79d43f759abf979a635 # v1.0.7
        with:
          run: |
            node_modules/.bin/flowfuse
          wait-on: |
            http://localhost:3000
          tail: true
          wait-for: 2m
          log-output: stderr,stdout
          log-output-if: failure
      - name: test access
        run: |
          curl -L -v http://localhost:3000

  notify-slack:
    name: Notify about test failure
    needs: [install]
    if: failure()
    runs-on: ubuntu-latest

    steps:
    - name: Notify Slack
      uses: FlowFuse/github-actions-workflows/actions/slack_notification@slack_notification/v1
      with:
        bot-token: ${{ secrets.SLACK_GHBOT_TOKEN }}
        mode: channel
        blocks: |
          [
            { "type": "header", "text": { "type": "plain_text", "text": ":x: ${{ github.workflow }} workflow failed", "emoji": true } },
            { "type": "divider" },
            { "type": "section", "text": { "type": "mrkdwn", "text": "<${{ github.server_url }}/${{ github.repository }}/actions/workflows/install-test.yaml|${{ github.workflow }}> workflow failed to complete successfully." } },
            { "type": "section", "text": { "type": "mrkdwn", "text": "*Workflow run:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View>" } }
          ]
