name: Project automations
on:
  issues:
    types:
      - opened
jobs:
  add_issue_to_relevant_boards:
    uses: flowfuse/github-actions-workflows/.github/workflows/project-automation.yaml@project-automation/v1
    secrets:
      app-client-id: ${{ secrets.GH_BOT_APP_ID }}
      app-private-key: ${{ secrets.GH_BOT_APP_KEY }}
